CREATE TABLE properties (
    id              UUID           PRIMARY KEY DEFAULT gen_random_uuid(),
    title           VARCHAR(200)   NOT NULL,
    slug            VARCHAR(220)   NOT NULL UNIQUE,
    description     TEXT,
    price           NUMERIC(15,2)  NOT NULL,
    area            NUMERIC(10,2),
    bedrooms        INTEGER,
    suites          INTEGER,
    bathrooms       INTEGER,
    parking_spots   INTEGER,
    address         VARCHAR(255),
    neighborhood    VARCHAR(100),
    city            VARCHAR(100)   NOT NULL,
    state           VARCHAR(2)     NOT NULL,
    zip_code        VARCHAR(9),
    deal_type       VARCHAR(10)    NOT NULL,
    featured        BOOLEAN        NOT NULL DEFAULT FALSE,
    status          VARCHAR(10)    NOT NULL DEFAULT 'ACTIVE',
    external_url    TEXT,
    category_id     UUID           NOT NULL REFERENCES categories(id),
    created_at      TIMESTAMP      NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP      NOT NULL DEFAULT NOW()
);
